# Default values for openidm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

# Top level domain. Used to create the ingress
domain: .forgeops.com

config:
  # Name of the shared pvc for our configuration. If using the frconfig helm chart, this is the default.
  claim: frconfig
  # Path to our project
  path: /git/config/default/idm/sync-with-ldap-bidirectional

image:
  repository: gcr.io/engineering-devops
  # For development use Always
  pullPolicy: Always
  #pullPolicy: IfNotPresent
  tag: 6.5.0

# If you set this to true, you must have a TLS secret with the same name as the FQDN.
useTLS: false

# Specific values
openidm:
  repo:
    host: userstore-0.userstore
    port: 1389
    user: cn=Directory Manager
    password: password
  #  schema: openidm
  #  databaseName: openidm
  # Optional client secret for AM/IDM integration:
  idpconfig:
    clientsecret: password

# Optional - if there is a DJ userstore configured
#userstore:
#  host: userstore-1.userstore
#  password: password
#  port: 1389

service:
  name: openidm
  type: NodePort
  externalPort: 80
  internalPort: 8080

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 1024Mi


# Used to form the FQDN  - see _helpers.tpl
component: openidm

# Default log level. See templates/configmap/logging.properties. For example, you can use FINE here to
# see fine grained logging output using kubectl logs.
logLevel: INFO

ingress:
  class: nginx
  annotations:
    # Nginx specific annotations
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
